#!/usr/bin/env python3
"""Regenerate REPORT.md from the frozen A/B verdicts.

Why this exists: the evidence file is only auditable if the human-readable
index is derived from it, not hand-written. Re-run after regenerating
verdicts.jsonl so the counts can never drift from the JSONL.

Usage:
    python3 tests/evidence/rules-20261006/generate_report.py
"""
import hashlib
import json
import os
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
BASE_REV = "2c1b4c5"
GEN_CMD = (
    "python3 tests/ab_rules.py --corpus tests/evidence/rules-20261006/candidates.jsonl \\\n"
    "  --base 2c1b4c5 --store data/topics.jsonl \\\n"
    "  --jsonl tests/evidence/rules-20261006/verdicts.jsonl --show 100000"
)


def rows(path):
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def change(row):
    return (row["base_keep"], row["base_tags"], row["base_score"]) != \
           (row["new_keep"], row["new_tags"], row["new_score"])


def line(row, title=True):
    tags = lambda r, k: ",".join(r[k]) or "-"  # noqa: E731
    out = [f"- `{row['url']}`"]
    if title:
        out.append(f"  - {row['title']}")
    out.append(
        f"  - gate: `{row['base_keep']}` → `{row['new_keep']}`; "
        f"tags: `{tags(row, 'base_tags')}` → `{tags(row, 'new_tags')}`; "
        f"score: `{row['base_score']}` → `{row['new_score']}`"
    )
    return out


def main():
    cand = rows(HERE / "candidates.jsonl")
    verdicts = rows(HERE / "verdicts.jsonl")
    c = [r for r in verdicts if r["kind"] == "candidate"]
    s = [r for r in verdicts if r["kind"] == "store"]
    assert len(c) == len(cand), (len(c), len(cand))

    gate = [r for r in c if r["base_keep"] != r["new_keep"]]
    tag = [r for r in c if r["base_keep"] and r["new_keep"] and change(r)]
    purge = [r for r in s if r["base_keep"] and not r["new_keep"]]
    retag = [r for r in s if r["base_keep"] and r["new_keep"] and change(r)]
    untagged = [r for r in s if r["new_keep"] and not r["new_tags"]]

    doc = []
    doc += [
        "# Rules Fix Evidence — 2026-10-06",
        "",
        "## Frozen Input",
        "",
        f"- Baseline: git `{BASE_REV}` (`fetch.py` only), compared with this checkout's working tree.",
        f"- Input: `candidates.jsonl`, exactly **{len(cand)}** pre-filter rows / "
        f"**{len({r['url'] for r in cand})}** distinct URLs / **{len({r['title'] for r in cand})}** distinct titles.",
        f"- Candidate SHA-256: `{sha(HERE / 'candidates.jsonl')}`",
        f"- Full verdict output: `verdicts.jsonl`, exactly **{len(verdicts)}** rows: "
        f"{len(c)} candidate rows plus {len(s)} store rows.",
        f"- Verdict SHA-256: `{sha(HERE / 'verdicts.jsonl')}`",
        "- Generation command:",
        "",
        "```bash",
        GEN_CMD,
        "```",
        "",
        "`verdicts.jsonl` is the complete row-by-row evidence: every input URL has a candidate verdict; "
        "every store URL has a store verdict. It retains unchanged rows too. The lists below are the "
        "human-readable index of every changed row, not a sample. The report itself is generated by "
        "`generate_report.py` from that JSONL.",
        "",
        f"## Candidate Differences ({len(gate) + len(tag)} of {len(c)})",
        "",
        f"### Gate Changed ({len(gate)})",
        "",
    ]
    for r in gate:
        doc += line(r)
    doc += ["", f"### Tags/Score Changed While Kept ({len(tag)})", ""]
    for r in tag:
        doc += line(r)
    doc += [
        "",
        f"## Store Impact ({len(purge)} purged / {len(retag)} retagged of {len(s)})",
        "",
        "The store is not rewritten by this change: these are what a future refresh would do.",
        "",
        f"### Would Be Purged ({len(purge)})",
        "",
    ]
    for r in purge:
        doc += [f"- `{r['url']}`", f"  - {r['title']}", f"  - stored tags: `{','.join(r['stored_tags']) or '-'}`"]
    doc += ["", f"### Would Be Retagged ({len(retag)})", ""]
    for r in retag:
        doc += [
            f"- `{r['url']}`",
            f"  - {r['title']}",
            f"  - stored: `{','.join(r['stored_tags']) or '-'}` / `{r['stored_score']}` → "
            f"re-scored: `{','.join(r['new_tags']) or '-'}` / `{r['new_score']}`",
        ]
    doc += ["", "### Kept But Still Untagged After Refresh ({})".format(len(untagged)), ""]
    for r in untagged:
        doc += [f"- `{r['url']}`", f"  - {r['title']}"]
    doc += [
        "",
        "## Interpretation",
        "",
        f"- Gate: {len({r['title'] for r in c})} unique candidate titles; the URL-granular JSONL is why the "
        f"changed row count exceeds the title-level diff.",
        f"- Removals ({sum(1 for r in gate if not r['new_keep'])}) are completed/expired, requests, questions, "
        "test/tool posts, proxy content, or negative product news; "
        f"additions ({sum(1 for r in gate if r['new_keep'])}) are AI-API offers the old gate dropped.",
        "- Tags: uppercase `CDK` now follows the lowercase normalization already used by the scorer; `低至` gains "
        "`优惠渠道`; a percentage after `送` no longer becomes a truncated amount; an official-price `号池` no "
        "longer gains `免费放粮` without an actual free signal.",
        "- Store `base_*` fields are computed by running the baseline gate and scorer, not assumed from "
        "membership in the store.",
        "",
    ]
    (HERE / "REPORT.md").write_text("\n".join(doc), encoding="utf-8")
    print(f"[report] {len(gate)} gate / {len(tag)} tag candidate rows, "
          f"{len(purge)} purge / {len(retag)} retag store rows, {len(untagged)} untagged kept")


if __name__ == "__main__":
    main()
